[package]
name = "rinth-midi"
version = "0.0.1"
edition = "2021"
publish = false
license-file = "../LICENSE"
authors = [ "Ivan Bushchik <ivabus@ivabus.dev>" ]

[dependencies]
rinth-types = { path="../rinth-types" }
clap = { version = "4.4.18", features = ["derive"] }
midly = "0.5.3"
